### PR TITLE
implement-none standard for wsjt-x 2.1.0 rc5

### PR DESCRIPTION
**Pull request by phdlee**
Implemented Decoding for 'None standard' protocol.

### CODE REVIEW

**Comment by kgoba** [comment]
Hi KD8CEC! Glad you find this library interesting and more over contributing to it!
I'll be glad to merge your implementation. I believe more work will have to be done to get the non-standard calls to work properly (they have to be hashed as I understand to be later displayed), but this is a great start!

By the way, how are you using ft8_lib - on a desktop, on a RPi or some other way?

**Comment by phdlee** [comment]
Thank you for accept about pullrequest. 
You are right. To implement 'None Standard Callsign',  need to generate and manage 10, 12, and 22 Hash codes.
I am writing code to make both C    and C available. When the test is completed, I will 'pull request'.
Thanks for sharing the cool code.

**Comment by kgoba** [comment]
I think now it's also interesting to look at FT4 protocol, as it should be easy to implement with this existing code, you only need to change some DSP routines. I have not had time for that yet.

**Comment by phdlee** [comment]
Excellent, I also have a great interest in FT4.

**Pull request merged**
